import { Inter } from "next/font/google";
import "./blueygrey.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tours of Belfast",
  description: "Generated by create next app",
};

export default function BlueyLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>

    </html>

  );
}

