import { Inter } from "next/font/google";
import "./../globals.css";
import BottomNav from "../../components/BottomNavTours";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ToursLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>

    </html>

  );
}

